Cora:
  seed: 39788
  learning_rate: 0.01
  input_dim: 1433
  hidden: 128
  proj_middim: 128
  proj_outdim: 128
  encoder: gcn
  layer_num: 2
  walk_step: 10
  restart_ratio: 0.5
  graph_num: 128
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.3
  tau: 0.4
  epochs: 500
  weight_decay: 0.0005
  optimizer: sgd
  patience: 500
  inductive: False
Citeseer:
  seed: 38108
  learning_rate: 0.01
  input_dim: 3703
  hidden: 256
  proj_middim: 256
  proj_outdim: 256
  encoder: gcn
  layer_num: 2
  walk_step: 10
  restart_ratio: 0.5
  graph_num: 128
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.4
  drop_feature_rate_2: 0.5
  tau: 0.7
  epochs: 300
  weight_decay: 0.0005
  optimizer: sgd
  patience: 300
  inductive: False
Pubmed:
  seed: 23344
  learning_rate: 0.001
  input_dim: 500
  hidden: 256
  proj_middim: 256
  proj_outdim: 256 # 128
  encoder: gcn
  layer_num: 2
  walk_step: 20
  restart_ratio: 0.8
  graph_num: 256
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.1
  epochs: 500
  weight_decay: 0.0005
  optimizer: adamw
  patience: 500
  inductive: False
DBLP:
  seed: 83521
  learning_rate: 0.001
  input_dim: 1639
  hidden: 256
  proj_middim: 256
  proj_outdim: 256
  encoder: gcn
  layer_num: 2
  walk_step: 10
  restart_ratio: 0.5
  graph_num: 128
  drop_edge_rate_1: 0.1
  drop_edge_rate_2: 0.2
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.3
  tau: 0.8
  epochs: 500
  weight_decay: 0.0005
  optimizer: adamw
  patience: 500
  inductive: False
Cornell:
  seed: 39788
  learning_rate: 0.001
  input_dim: 1703
  hidden: 64
  proj_middim: 64
  proj_outdim: 64
  encoder: gcn
  layer_num: 2
  walk_step: 10
  restart_ratio: 0.0
  graph_num: 256
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.3
  tau: 0.4
  epochs: 200
  weight_decay: 0.0005
  optimizer: sgd
  patience: 20
  inductive: False
Texas:
  seed: 39788
  learning_rate: 0.001
  input_dim: 1703
  hidden: 64
  proj_middim: 64
  proj_outdim: 64
  encoder: gcn
  layer_num: 2
  walk_step: 20
  restart_ratio: 0.0
  graph_num: 256
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.3
  tau: 0.4
  epochs: 200
  weight_decay: 0.0005
  optimizer: sgd
  patience: 20
  inductive: False
Wisconsin:
  seed: 39788
  learning_rate: 0.001
  input_dim: 1703
  hidden: 64
  proj_middim: 64
  proj_outdim: 64
  encoder: gcn
  layer_num: 2
  walk_step: 10
  restart_ratio: 0.0
  graph_num: 256
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.3
  drop_feature_rate_1: 0.2
  drop_feature_rate_2: 0.3
  tau: 0.4
  epochs: 200
  weight_decay: 0.0005
  optimizer: sgd
  patience: 20
  inductive: False

